root: true
env:
  browser: true
  es2021: true
  node: true
globals:
  defineOptions: readonly
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - plugin:@typescript-eslint/recommended
overrides: [ ]
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  parser: '@typescript-eslint/parser'
  jsxPragma: React,
  ecmaFeatures:
    jsx: true
plugins:
  - vue
  - '@typescript-eslint'
rules: {}
