// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../components/common/AppProvider.vue')['default']
    DarkModeContainer: typeof import('./../components/common/DarkModeContainer.vue')['default']
    HoverContainer: typeof import('./../components/common/HoverContainer.vue')['default']
    IconCustomVue: typeof import('~icons/custom/vue')['default']
    IconParkFullScreenOne: typeof import('~icons/icon-park-outline/full-screen-one')['default']
    IconParkHome: typeof import('~icons/icon-park-outline/home')['default']
    IconParkMoon: typeof import('~icons/icon-park-outline/moon')['default']
    IconParkOffScreenOne: typeof import('~icons/icon-park-outline/off-screen-one')['default']
    IconParkSunOne: typeof import('~icons/icon-park-outline/sun-one')['default']
    IconParkTranslate: typeof import('~icons/icon-park-outline/translate')['default']
    Logo: typeof import('./../components/common/Logo.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemLogo: typeof import('./../components/common/SystemLogo.vue')['default']
  }
}
